title = "Run period for data taking with prototype Timepix3 detector"
# list of the run periods defined in the file
runPeriods = ["RunPrototypeSurface", "RunPrototypeUnderground"]

[RunPrototypeSurface]
start = 2022-05-01
stop = 2022-06-30
# either as a sequence of run numbers
validRuns = []
# or as simply a range given as start and stop values
firstRun = 0
lastRun = 46

[RunPrototypeUnderground]
start = 2022-07-01
stop = 2022-10-01
# either as a sequence of run numbers
validRuns = []
# or as simply a range given as start and stop values
firstRun = 47
lastRun = 120
