[General]
outpath = "" # the output path in which the generated H5 files will be placed
# prefixes for the different resulting files
tpx3Prefix = "tpx3_" # the prefix of the output file after `readTpx3`
rawPrefix = "raw_" # the prefix of the output file after `raw_data_manipulation`
recoPrefix = "reco_" # the prefix of the output file after `reconstruction`
# path to the `config.toml` used by `raw_*`, `reconstruction`, ...
rawRecoConfigFile = "" # default: "" (uses config `Analysis/ingrid/config.toml`)

# parameters that control the plots to be created from the `plotData` call
plotDataSuffix = "--ingrid --occupancy --totPerPixel --compiledCustom --backend bGgPlot"