sudo: required

os:
  - linux

language: c
dist: bionic

matrix:
  include:
    # Build and test against the master (stable) and devel branches of Nim
    # Build and test using both gcc and clang
    - os: linux
      env: CHANNEL=stable
      compiler: gcc

    - os: linux
      env: CHANNEL=devel
      compiler: gcc

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

addons:
  apt:
        packages:
                - libhdf5-100
                - libhdf5-dev
                - libgfortran3
                - libsz2
                - libaec-dev

install:
  - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
  - sh init.sh -y
  - export PATH=$HOME/.nimble/bin:$PATH
  - nimble refresh -y
  - choosenim $CHANNEL

script:
  - nimble install -y "https://github.com/vindaar/shell"
  - nim e buildTpa.nims
  - nim e runTests.nims
