title = "Run period 1 of CAST, 2014/15"
# list of the run periods defined in the file
runPeriods = ["Run1"]

[Run1]
start = 2014-10-21
stop = 2015-11-23
# use runs only as start / stop. For important things we parse the run file
# to know which runs to ignore
firstRun = 0
lastRun = 548
additional = '''
Runs from 0 to 79 are the CDL runs from 2014, while the runs from 127 to 548 cover
the actual CAST data runs.
'''