# this TOML document is used to configure the raw data manipulation, reconstruction and likelihood
# tools

[Calibration]
showPlots = false
plotDirectory = "out"
# minutes for binning of gas gain
gasGainInterval = 90
# decides if `charge` dataset is deleted when running `only_charge`.
# by default this is disabled, because the attributes of the dataset
# contain things beyond the actual charge calibration!
deleteChargeDset = true
# the gas gain vs energy calibration factor computation to use
# - "": the default of just one gas gain per calibration run based on
#       one gas gain interval for each run
# - "Mean": use the mean of all gas gain time slices
# - "Individual": use the factors obtained from one Fe fit per gas gain slice
gasGainEnergyKind = "Individual"

[RawData]
plotDirectory = "out"
