# this TOML document is used to configure the raw data manipulation, reconstruction and likelihood
# tools

[Calibration]
        showPlots = false
        plotDirectory = "out"
        gasGainInterval = 30.0 # minutes for binning of gas gain