[General]
        allowedChips = [ 3, 4 ]
        outputFormat = "json" # <- store either as "json" or "org"

[InGrid]
        dsets = ["length", "width", "skewnessLongitudinal", "skewnessTransverse",
                 "kurtosisLongitudinal", "kurtosisTransverse", "rotationAngle",
                 "eccentricity", "fractionInTransverseRms", "lengthDivRmsTrans"]
[Fadc]
        dsets = ["minvals", "fallTime", "riseTime"]

[Occupancy]
