[General]
        allowedChips = [ 3 ]

[InGrid]
        dsets = ["length", "width", "skewnessLongitudinal", "skewnessTransverse",
                 "kurtosisLongitudinal", "kurtosisTransverse", "rotationAngle",
                 "eccentricity", "fractionInTransverseRms", "lengthDivRmsTrans"]
[Fadc]
        dsets = ["minvals", "fallTime", "riseTime"]

[Occupancy]
