[General]
        #allowedChips = [3] #[0, 1, 2, 3, 4, 5, 6]
        #allowedRuns = [126]
        outputFormat = "org" # <- store either as "json" or "org"
        filetype = "pdf"
        plotlySaveSvg = false
        mplShowPlots = false

[InGrid]
        #dsets = ["length", "width", "skewnessLongitudinal", "skewnessTransverse",
        #         "kurtosisLongitudinal", "kurtosisTransverse", "rotationAngle",
        #         "eccentricity", "fractionInTransverseRms", "lengthDivRmsTrans",
        #         "hits"]
        dsets = ["energyFromCharge"]
[Fadc]
        dsets = ["minvals", "fallTime", "riseTime"]

[Occupancy]

[Cuts]
cuts = []
# Example cut
# [Cuts.1] # name is just 1
# applyFile = [] # apply this cut to the input files listed in this array
# applyTo = [] # if any given, apply this cut to all plots of the datasets in this array
# dset = toaLength # dataset the cut applies to
# min = 0.0 # minimum allowed value
# max = 20.0 # maximum allowed value

[Cuts.1]
applyFile = ["reco_tpx3_background.h5", "lhood_tpx3_background_cast_cdl.h5"]
applyDset = [] # if any given, apply this cut to all plots of the datasets in this array
dset = "toaLength" # dataset the cut applies to
min = 0.0 # minimum allowed value
max = 20.0 # maximum allowed value

[MaskRegions]
# in theory this could also identify itself by chip name & run period, but that's a bit restrictive
# example mask region
# regions = [1]
# [MaskRegions.1]
# applyFile = ["reco_tpx3_background.h5"]
# applyDset = []
# x = [150, 250] # mask x range from <-> to
# y = [130, 162] # mask y range from <-> to

regions = [1, 2]
[MaskRegions.1]
applyFile = ["reco_tpx3_background.h5", "lhood_tpx3_background_cast_cdl.h5"]
applyDset = []
x = [150, 250] # mask x range from <-> to
y = [130, 162] # mask y range from <-> to

[MaskRegions.2]
applyFile = ["reco_tpx3_background.h5", "lhood_tpx3_background_cast_cdl.h5"]
applyDset = []
x = [125, 135] # mask x range from <-> to
y = [110, 120] # mask y range from <-> to


[Bins]
# settings for the binning in different histograms
[Bins.BinRange]
hits                 = [0.0, 500.0]
energyFromPixel      = [0.0, 15000.0]
energyFromCharge     = [0.0, 15.0]
sumTot               = [0.0, 20000.0]
kurtosisLongitudinal = [-5.0, 10.0]
kurtosisTransverse   = [-2.0, 8.0]
rmsLongitudinal      = [0.0, 6.0]
rmsTransverse        = [0.0, 6.0]
eccentricity         = [1.0, 8.0]
ToT                  = [0.0, 250.0]
lengthDivRmsTrans    = [2.0, 8.0]
energyCut            = [0.0, 10000.0]
length               = [0.0, 14.5]
minvals              = [-0.6, 0.0]
riseTime             = [2.0, 502.0]
fallTime             = [7.0, 707.0]
totPerPixel          = [-0.5, 300.5]

[Bins.NumBins]
hits                 = 500
energyFromPixel      = 100
energyFromCharge     = 500
sumTot               = 100
kurtosisLongitudinal = 100
kurtosisTransverse   = 100
rmsLongitudinal      = 100
rmsTransverse        = 200
eccentricity         = 500
ToT                  = 250
lengthDivRmsTrans    = 100
energyCut            = 100
length               = 300
minvals              = 100
riseTime             = 100
fallTime             = 50
totPerPixel          = 101

[Bins.BinSize]
riseTime             = 20.0
fallTime             = 20.0
FeSpectrum           = 1.0
FeSpectrumCharge     = 100.0
totPerPixel          = 1.0
toaLength            = 1.0
